theckman/yacspin

- Gopkg.lock
- Gopkg.toml
- colors_test.go
- spinner.go
- spinner_test.go
- vendor/github.com/google/go-cmp/LICENSE
- vendor/github.com/google/go-cmp/cmp/compare.go
- vendor/github.com/google/go-cmp/cmp/export_panic.go
- vendor/github.com/google/go-cmp/cmp/export_unsafe.go
- vendor/github.com/google/go-cmp/cmp/internal/diff/debug_disable.go
- vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go
- vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go
- vendor/github.com/google/go-cmp/cmp/internal/flags/flags.go
- vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_legacy.go
- vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_recent.go
- vendor/github.com/google/go-cmp/cmp/internal/function/func.go
- vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
- vendor/github.com/google/go-cmp/cmp/internal/value/pointer_unsafe.go
- vendor/github.com/google/go-cmp/cmp/internal/value/sort.go
- vendor/github.com/google/go-cmp/cmp/internal/value/zero.go
- vendor/github.com/google/go-cmp/cmp/options.go
- vendor/github.com/google/go-cmp/cmp/path.go
- vendor/github.com/google/go-cmp/cmp/report.go
- vendor/github.com/google/go-cmp/cmp/report_compare.go
- vendor/github.com/google/go-cmp/cmp/report_reflect.go
- vendor/github.com/google/go-cmp/cmp/report_slices.go
- vendor/github.com/google/go-cmp/cmp/report_text.go
- vendor/github.com/google/go-cmp/cmp/report_value.go
This adds the first round of tests for the `*Spinner` type, and simplified the
`New()` constructor function in the process. To use the `go-cmp` package, I also
needed to export the fields of the unexported `character` type.
> Add first round of tests for *Spinner type and associated functions

- spinner.go
- spinner_test.go
This change adds more tests to project coverage, as well as updates the
constructor for more implcit testing (through message use for setting values).
This also updates the `CharSet()` method to return an error so we can do input
validation, so that we only recieve valid character sets.
> Add more tests for Spinner methods; add error return to CharSet()

- spinner.go
- spinner_test.go
Atomic values made sense when the original implementation was simpler, but as it
grew the addtional features were wedged-in even when atomic values no longer
made sense. This was because the values were related to other fields on the
struct so they couldn't be truly atomic.
Let's instead use a mutex so spinner paints are consistent, and so the
implementationn is simpler.
> Remove usage of sync/atomic.Value in favor of mutex

- spinner.go
- spinner_test.go
This adds support for printing on Windows, using a more rudimentary method for
clearing the screen. Windows terminals don't understand VT100 / ANSI terminal
escape sequences, so the methods used for OS X and Linux aren't applicable.
When on Windows, it tracks the number of wrtten bytes and on erase writes a
carriage return and that number of plain spaces to overwrite the characters
followed by a final carriage return.
> Add support for Windows printing

- spinner.go
- spinner_test.go
This adds a new configuration field `SuffixAuoColon`, which adds a mode to
automatically append a colon and a space to the suffix if there is a message
present.
> Add support for automatic suffix delimiter using colon

- README.md
- spinner.go
- spinner_test.go
Prior to this, your spinner content could only be updated as often as the
spinner was rendering. Data liveliness was tied to your animation speed, which
meant for faster updates you had to sacrifice what your spinner animation looked
like.
This change separates the two, so that calling a method like `Message()` should
update the spinner's message in near realtime without the spinner itself being
animated.
> Separate updates to content from spinner animation

- spinner.go
- spinner_test.go
Without this change, updates of data reset the timer making the animation no
longer render smoothly.
This also fixes some potential race conditions with `Start()` or `Stop()` and
any of the setter methods.
> Do not reset timer when painting a data update; fix races

- spinner.go
Some of the things we were doing inside of the mutex weren't protected by the
mutex itself. This reshuffles the code a bit to consider that and do as little
inside of the mutex as we can.
> Reduce number operations we do inside of the mutex

- spinner.go
- spinner_test.go
It seems reasonable that someone may want a paused spinner to be stopped,
without the user seeing another animation or data update. This supports `Stop()`
and `StopFail()` working on a spinner whose `Status()` is `SpinnerPaused`.
> Support stopping a paused spinner

- spinner_test.go
It makes the tests easier to read, especially since it adds consistency with `spinner.go`.
> Update tests to use internal spinner status constants

- spinner.go
- spinner_test.go
This removes the `Delay` field from the `Config` struct. This also removes two
methods from the `*Spinner` type: `Delay()` and `Active()`.
> Remove identifiers deprecated in v0.8.0

- spinner.go
This change is a small update to help make the spinner a bit more robust.
The first increases internal channel buffer size for frequency updates, to hopefully
non-blocking write dropping an update. The buffer size increase is arbitrary,
and calling .Frequency() in a hot loop could still result in dropped updates.
The second is the removal of a mutex lock within the Status() method, and an
unnecessary nil check. There is not a need for either of them based on how
the *Spinner is constructed.
The third is some refinemennt of the documentation both in comments on exported
identifiers, and comments within the source code.
> Reduce missed Frequency updates, reduce mutex locks, update docs

- .github/workflows/tests.yaml
They seem to have some weird math issues around code refactors, where you can
end up changing the coverage by a hundredth of a percent, even though you've
effectively not changed the coverage. This ends up erroneously failing the
build.
So let's remove it and just print coverage reports.
> Remove codecov due to it falsely failing builds

- spinner.go
- spinner_test.go
This change introduces a 2KB (growable) byte buffer, to sit in between the
painting function(s) and stdout. Previously, as we were animating the spinner we
would write the bytes directly to stdout as we were generating the animation.
This change makes it so that most of our writes are to an in-memory buffer, and
then we only have one system call to write to the actaul terminal the contents
of that buffer.
This should act like a bit of a frame buffer, so if if anyone was experiencing
any sort of stutter, where they could see the cursor as the spinner was
animated, I believe this should result in a smoother adnimation.
> Use a byte buffer to reduce number of write calls to stdout

- README.md
- spinner.go
- spinner_test.go
This change updates the internals of the spinner to support rendering the
animation at the end of the line instead of the beginning. This is exposed via
the Config.SpinnerAtEnd struct field, and related method.
> Add support for rendering animated spinner at the end of the line

- spinner.go
- spinner_test.go
This needs to be done, otherwise the buffer will print null bytes at the
beginning of the first line.
> Reset the buffer when constructing the spinner

- spinner.go
The changes highlight how the different types work together, and a gotcha to be
aware of with the default configuration hiding the terminal cursor.
> Improve comments around the Config and Spinner types

- spinner.go
- spinner_test.go
This updates the spinner only append a colon (`:`) onto the suffix if the
suffix is set, and it contains more than space characters.
> Do not apply SuffixAutoColon when suffix is only space characters

- character_sets.go
The project where we've gotten the spinners from has added 10 more of them, and
added a new license header to the file we copied them from. So we import both
the new spinners and the new copyright header, while adding my own copyright for
the delcared modifications made to the file.
> Import more CharSets and license header from briandowns/spinner

- character_sets_test.go
These should always work out of the box, so may as well build an assertion for
it.
> Add a test to make sure all CharSets don't cause .CharSet() errors

- spinner.go
- spinner_test.go
I believe the code will panic otherwise. No use causing that sort of behavior
for consumers if we do know they've provided an invalid configuration.
> Fail Start() if no CharSet has been set for the spinner

- README.md
- spinner.go
- spinner_test.go
This change introduces a substantial change to how we handle the TTY discovery
when constructing the spinner. It adds a new bitflag field to the Config struct,
TerminalMode, that allows consumers to control whether the spinner tries to
automatically disocver if it's within a TTY and/or a dumb terminal. It also
allows you to override the behaviors, if you know the automatic mode won't do
what you want.
A side effect of this change is that you can now manually step the spinner
animation by setting TerminalMode: ForceNoTTYMode, and then starting the spinner
and calling the Message() method when you want to animate the spinner. To permit
this, the Frequency field in the Config struct is now not required when calling
the New() function. An error will be generated on Start() if it's within a …
> Add TerminalMode config; make Frequency optional when not TTY

- character_sets_test.go
When `yacspin` adds its own pre-created spinners to the `CharSets` variable,
they will start at index 500 to ideally avoid conflicts with spinners pulled-in
from github.com/briandowns/spinner. However, if that change was made today this
test would likely fail.
So let's update the test to range over the map directly, instead of using
indexes, to avoid this breaking in the future.
> Make CharSets test less brittle to future changes
